### ISSUE TITLE
selfIntersections doesn't work when diagonals cross inside polygon

### ISSUE THREAD

**Issue by robhawkes** [tmpvar/polygon.js#4]
The following polygon is self-intersecting but the `selfIntersections` method doesn't pick anything up:

Polygon:
```javascript
var polygon = polygonjs([
  [0, 0], // 1
  [10, 0], // 2
  [0, 10], // 3
  [10, 10], // 4
  [0, 0] // 1
]);
```

(bad) ASCII:
```
3---4
 \ /   
 / \  
1---2
```

If I change the final point from `[0, 0] ` to `[5, -5]` then a self-intersection is picked up.

Is this expected behaviour? I need to be able to pick up these kind of intersections.

**Comment by tmpvar** [comment]
oh hey! yeah, this is definitely a bug.  I know of a much more robust way of doing this and can implement this evening

**Comment by tmpvar** [comment]
I've been moving away large grab-bags of functionality like polygon.js, and it looks like you are using a polygon defined by an array of 2 component arrays (vectors).  I've written up a lib that should robustly return you _all_ of the self intersections.

demo: http://requirebin.com/?gist=b73e86cbdfe7558271a7
repo: https://github.com/tmpvar/2d-polygon-self-intersections

let me know how that works for you!

**Comment by tmpvar** [comment]
ok, I realize that there is a disparity between using an array of arrays and an array of vec2's - to remedy that I've pushed 2d-polygon-self-intersections@1.1.0 which includes support for array of vec2's and array of arrays

if you are using polygon to manage vec2s then you can do `isects(polygon.points)`

**Comment by robhawkes** [comment]
Awesome, thank you! Didn't expect such a speedy remedy, I appreciate it.

The new library picks up the intersection now but the returned coordinates are incorrect (at least the Y axis). [I've filed an issue in the new repo](https://github.com/tmpvar/2d-polygon-self-intersections/issues/1) as to not clutter this one.
